Version for DSM 7

diff --git a/synology/scripts/start-stop-status b/synology/scripts/start-stop-status
--- a/synology/scripts/start-stop-status
+++ b/synology/scripts/start-stop-status
@@ -28,53 +28,42 @@ start_daemon ()
     #Look for any ss-<ssserver>-<name>.json config files in configuration etc folder, and optionaly ss-<ssserver>-<name>.params
     while read -r CONF_FILE
     do
-        local SS_SERVER CONF_NAME PID_FILE PARAMS CMD
+        local SS_SERVER CONF_NAME PID_FILE CMD
 
         SS_SERVER=$(echo "$CONF_FILE" | sed -E 's,'"$CONFFILES_REGEX"',\2,')
         CONF_NAME=$(echo "$CONF_FILE" | sed -E 's,'"$CONFFILES_REGEX"',\4,')
+        CONF_FULLNAME=$(echo "$CONF_FILE" | sed -E 's,'"$CONFFILES_REGEX"',\2\3,')
 
-        PID_FILE="$PID_DIR/$SS_SERVER${CONF_NAME:+-$CONF_NAME}.pid"
+        PID_FILE="$PID_DIR/$SS_SERVER$CONF_FULLNAME.pid"
 
-        # Allow to have specific parameters in ss-<server>-xxx.params
-        # not really needed because most parameters can be specified in the json file, so commented out
-        #PARAMS="$(grep '^-' $CONFIG_DIR/$SS_SERVER${CONF_NAME:+-$CONF_NAME}.params 2>/dev/null)"
-
-        CMD="$INSTALL_DIR/bin/$SS_SERVER $PARAMS -c $CONF_FILE -f $PID_FILE"
+        CMD="synosystemctl start pkg-$SS_SERVER@$CONF_FULLNAME"
 
         if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" > /dev/null 2>&1; then
             echo "  $SS_SERVER $CONF_NAME is already running"
         else
-            # tcp is inactive if option udp_only or -U (default is active)
+            # tcp is inactive if option udp_only (default is active)
             local tcpmode
-            if grep -E -q 'udp_only' "$CONF_FILE" || [ -z "${CMD##* -U*}" ]; then
+            if grep -E -q 'udp_only' "$CONF_FILE"; then
                 tcpmode=0
             else
                 tcpmode=1
             fi
 
-            # udp is active if option tcp_and_udp or udp_only or -u or -U (default is inactive)
+            # udp is active if option tcp_and_udp or udp_only (default is inactive)
             local udpmode
-            if grep -E -q 'tcp_and_udp|udp_only' "$CONF_FILE" || [ -z "${CMD##* -u*}" ] || [ -z "${CMD##* -U*}" ]; then
+            if grep -E -q 'tcp_and_udp|udp_only' "$CONF_FILE"; then
                 udpmode=1
             else
                 udpmode=0
             fi
 
-            # Run as root if this is ss-redir and with udp, otherwise as standard user
-            # needed because it seems DSM does not support (?) setcap cap_net_admin+ep ss-redir
-            if [ "$SS_SERVER" = "ss-redir" ] && [ "$udpmode" = 1 ]; then
-                $CMD
-                retcode=$?
-            else
-                /bin/su shadowsocks-libev -s /bin/sh -c "$CMD"
-                retcode=$?
-            fi
+            $CMD
+            retcode=$?
 
             if [ "$retcode" != 0 ]
             then
                 echo "Startup of $DNAME $SS_SERVER failed for config file $CONF_FILE" >> "$SYNOPKG_TEMP_LOGFILE"
             else
-                renice -5 "$(cat "$PID_FILE")"
                 started=1
             fi
 
@@ -128,9 +117,7 @@ stop_daemon ()
 
     while read -r PID_FILE
     do
-        kill "$(cat "$PID_FILE")"
-        wait_for_death 20 "$(cat "$PID_FILE")" || kill -9 "$(cat "$PID_FILE")"
-        rm -f "$PID_FILE"
+        synosystemctl stop "$(synosystemctl get-unit-by-pid "$(cat "$PID_FILE")")"
     done < <( find -L "$sourcefiles" -maxdepth 1 -regextype posix-extended -regex '.*/'"$PIDFILES_REGEX" -type f )
 }
 
@@ -189,9 +176,20 @@ setvars_unit_file ()
     UNIT_FILE="$CONFIG_DIR/$UNIT_SERVER.json"
 }
 
+exit_if_not_root ()
+{
+    if [ ! "$(id -u)" = "0" ]; then
+        echo "Cannot proceed because not root. Connect though SSH, run the following command and restart: sudo /var/packages/shadowsocks-libev/scripts/addprivileges" >> "$SYNOPKG_TEMP_LOGFILE"
+        echo "Cannot proceed because not root. Connect though SSH, run the following command and restart: sudo /var/packages/shadowsocks-libev/scripts/addprivileges"
+        exit 0 # We should exit 1 but this triggers a "repair", not what we want
+    fi
+}
+
 # script is run from unexisting home directory of homeless user, which bugs some functions, so go to /tmp instead
 # shellcheck disable=SC2164
 cd "${TMPDIR-/tmp}"
+
+exit_if_not_root
 
 case $1 in
     start)
