Always return status started to DSM so that the app icon appears for configuration

diff --git a/synology/scripts/start-stop-status b/synology/scripts/start-stop-status
--- a/synology/scripts/start-stop-status
+++ b/synology/scripts/start-stop-status
@@ -13,12 +13,12 @@ SCRIPT_TPROXY="$SCRIPT_DIR/tproxy.sh"
 
 start_daemon ()
 {
-	local sourcefiles
-	if [ "$1" = "" ]; then
-		sourcefiles="$CONFIG_DIR" # normal launch: start everything in the folder
-	else
-		sourcefiles="$1" # unit launch: only 1 file
-	fi
+    local sourcefiles
+    if [ "$1" = "" ]; then
+        sourcefiles="$CONFIG_DIR" # normal launch: start everything in the folder
+    else
+        sourcefiles="$1" # unit launch: only 1 file
+    fi
 
     local CONF_FILE started retcode tcpredir udpredir
     started=0
@@ -93,8 +93,8 @@ start_daemon ()
         # At least 1 daemon could start, update the used ports toward DSM if needed
         "$SCRIPT_DIR/gensc.sh"
     else
-        echo 'Nothing started: check config file(s) ss-(local|server|redir|tunnel|manager)[-confname].json in: '"$CONFIG_DIR" >> "$SYNOPKG_TEMP_LOGFILE"
-        exit 1
+        echo 'No shadowsocks service is currently started: create or check config file(s) ss-(local|server|redir|tunnel|manager)[-confname].json using the user interface or directly in folder: '"$CONFIG_DIR" >> "$SYNOPKG_TEMP_LOGFILE"
+        exit 0 # Always return 0 because DSM does not show the config app if service is not considered started
     fi
 
     # Run network configuration scripts for ss-redir (iptables REDIRECT / TPROXY...)
@@ -119,18 +119,18 @@ stop_daemon ()
 {
     local PID_FILE
 
-	local sourcefiles
-	if [ "$1" = "" ]; then
-		sourcefiles="$PID_DIR" # normal launch: stop everything in the folder
-	else
-		sourcefiles="$PID_DIR/$1.pid" # unit stop: only 1 file
-	fi
+    local sourcefiles
+    if [ "$1" = "" ]; then
+        sourcefiles="$PID_DIR" # normal launch: stop everything in the folder
+    else
+        sourcefiles="$PID_DIR/$1.pid" # unit stop: only 1 file
+    fi
 
     while read -r PID_FILE
     do
-		kill "$(cat "$PID_FILE")"
-		wait_for_death 20 "$(cat "$PID_FILE")" || kill -9 "$(cat "$PID_FILE")"
-		rm -f "$PID_FILE"
+        kill "$(cat "$PID_FILE")"
+        wait_for_death 20 "$(cat "$PID_FILE")" || kill -9 "$(cat "$PID_FILE")"
+        rm -f "$PID_FILE"
     done < <( find -L "$sourcefiles" -maxdepth 1 -regextype posix-extended -regex '.*/'"$PIDFILES_REGEX" -type f )
 }
 
@@ -139,19 +139,19 @@ daemon_status_unit ()
     local CONF_FILE SS_SERVER CONF_NAME PID_FILE
 
     CONF_FILE="$1"
-	SS_SERVER=$(echo "$CONF_FILE" | sed -E 's,'"$CONFFILES_REGEX"',\2,')
-	CONF_NAME=$(echo "$CONF_FILE" | sed -E 's,'"$CONFFILES_REGEX"',\4,')
+    SS_SERVER=$(echo "$CONF_FILE" | sed -E 's,'"$CONFFILES_REGEX"',\2,')
+    CONF_NAME=$(echo "$CONF_FILE" | sed -E 's,'"$CONFFILES_REGEX"',\4,')
 
-	PID_FILE="$PID_DIR/$SS_SERVER${CONF_NAME:+-$CONF_NAME}.pid"
+    PID_FILE="$PID_DIR/$SS_SERVER${CONF_NAME:+-$CONF_NAME}.pid"
 
-	if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" > /dev/null 2>&1; then
-		[ -n "$2" ] || echo "  $SS_SERVER $CONF_NAME is running"
-		return 0
-	else
-		[ -n "$2" ] || echo "  $SS_SERVER $CONF_NAME is not running"
-		rm -f "$PID_FILE"
-		return 1	
-	fi
+    if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" > /dev/null 2>&1; then
+        [ -n "$2" ] || echo "  $SS_SERVER $CONF_NAME is running"
+        return 0
+    else
+        [ -n "$2" ] || echo "  $SS_SERVER $CONF_NAME is not running"
+        rm -f "$PID_FILE"
+        return 1
+    fi
 }
 
 # Status is True if at least 1 ss-<server> is running, False if none is running
@@ -177,7 +177,7 @@ wait_for_death ()
     local daemonpid=$2
     while [ "${counter}" -gt 0 ]; do
         kill -0 "$daemonpid" > /dev/null 2>&1 || return 0
-	counter=$((counter-1))
+    counter=$((counter-1))
         sleep 1
     done
     return 1
@@ -185,8 +185,8 @@ wait_for_death ()
 
 setvars_unit_file ()
 {
-	UNIT_SERVER=$(basename "$1" .json)
-	UNIT_FILE="$CONFIG_DIR/$UNIT_SERVER.json"
+    UNIT_SERVER=$(basename "$1" .json)
+    UNIT_FILE="$CONFIG_DIR/$UNIT_SERVER.json"
 }
 
 # script is run from unexisting home directory of homeless user, which bugs some functions, so go to /tmp instead
@@ -195,57 +195,58 @@ cd "${TMPDIR-/tmp}"
 
 case $1 in
     start)
-		if [ "$2" = "" ]; then
-			echo "Starting $DNAME ..."
-			start_daemon
-		else
-			setvars_unit_file "$2"
-			if [ ! -f "$UNIT_FILE" ]; then
-				echo "$UNIT_FILE not found"
-				exit 1
-			elif daemon_status_unit "$UNIT_FILE" 0; then
-				echo "$DNAME $UNIT_SERVER is already running"
-			else
-				echo "Starting $DNAME $UNIT_SERVER ..."
-				start_daemon "$UNIT_FILE"
-			fi
-		fi
-		;;
+        if [ "$2" = "" ]; then
+            echo "Starting $DNAME ..."
+            start_daemon
+            exit 0 # Always return 0 because DSM does not show the config app if service is not considered started
+        else
+            setvars_unit_file "$2"
+            if [ ! -f "$UNIT_FILE" ]; then
+                echo "$UNIT_FILE not found"
+                exit 1
+            elif daemon_status_unit "$UNIT_FILE" 0; then
+                echo "$DNAME $UNIT_SERVER is already running"
+            else
+                echo "Starting $DNAME $UNIT_SERVER ..."
+                start_daemon "$UNIT_FILE"
+            fi
+        fi
+        ;;
     stop)
-		if [ "$2" = "" ]; then
-			if daemon_status 0; then
-				echo "Stopping $DNAME ..."
-				stop_daemon
-			else
-				echo "$DNAME is not running"
-			fi
-		else
-			setvars_unit_file "$2"
-			if daemon_status_unit "$UNIT_FILE" 0; then
-				echo "Stopping $DNAME $UNIT_SERVER ..."
-				stop_daemon "$UNIT_SERVER"
-			else
-				echo "$DNAME $UNIT_SERVER is not running"
-			fi
-		fi
+        if [ "$2" = "" ]; then
+            if daemon_status 0; then
+                echo "Stopping $DNAME ..."
+                stop_daemon
+            else
+                echo "$DNAME is not running"
+            fi
+        else
+            setvars_unit_file "$2"
+            if daemon_status_unit "$UNIT_FILE" 0; then
+                echo "Stopping $DNAME $UNIT_SERVER ..."
+                stop_daemon "$UNIT_SERVER"
+            else
+                echo "$DNAME $UNIT_SERVER is not running"
+            fi
+        fi
         ;;
     status)
-		if [ "$2" = "" ]; then
-			if daemon_status; then
-				exit 0
-			else
-				echo "$DNAME is not running"
-				exit 3
-			fi
-		else
-			setvars_unit_file "$2"
-			if daemon_status_unit "$UNIT_FILE"; then
-				exit 0
-			else
-				exit 3
-			fi
-		fi
-		;;
+        if [ "$2" = "" ]; then
+            if daemon_status; then
+                exit 0
+            else
+                echo "$DNAME is not running"
+                exit 0 # Always return 0 because DSM does not show the config app if service is not considered started
+            fi
+        else
+            setvars_unit_file "$2"
+            if daemon_status_unit "$UNIT_FILE"; then
+                exit 0
+            else
+                exit 3
+            fi
+        fi
+        ;;
     log)
         echo "${LOG_FILE}"
         ;;
